mybatis:
  mapper-locations: classpath*:/mybatis/*/*Mapper.xml
spring:
  #main:
    #allow-bean-definition-overriding: true
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    password: root
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    useGlobalDataSourceStat: true
    username: root
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
swagger:
  enabled: true
logging:
  config: classpath:logback-spring.xml
provider:
  document:
    name: DEMO
    path: csp.nhsoft.cn/demo
    version: 1.0
    target: D:/springFox/demo/demo.json

